apiVersion: batch/v1
kind: Job
metadata:
  name: locust-master
  namespace: stress-test
  labels:
    name: locust-master
spec:
  completions: 1  # Number of master pods to run
  parallelism: 1  # Number of pods to run in parallel (can be adjusted)
  backoffLimit: 0  # Disable retries on pod failure
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: ton731/locust-cli
          env:
            - name: LOCUST_MODE
              value: master
          ports:
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
      restartPolicy: Never
