apiVersion: batch/v1
kind: Job
metadata:
  name: locust-worker
  namespace: tony-test
  labels:
    name: locust-worker
spec:
  completions: 1  # Number of worker pods to run
  parallelism: 1  # Number of pods to run in parallel (can be adjusted)
  backoffLimit: 0  # Disable retries on pod failure
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: ton731/locust-cli
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_URL
              value: locust-master
      restartPolicy: Never
