apiVersion: batch/v1
kind: Job
metadata:
  name: locust-master
  namespace: stress-test
  labels:
    name: locust-master
spec:
  completions: 1  # Number of master pods to run
  parallelism: 1  # Number of pods to run in parallel (can be adjusted)
  backoffLimit: 0  # Disable retries on pod failure
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: spector3702/locust-cli:latest
          env:
            - name: LOCUST_MODE
              value: master
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/gcloud-service-key.json
          ports:
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
          volumeMounts:
            - name: gcp-service-key
              mountPath: /app
      restartPolicy: Never
      volumes:
        - name: gcp-service-key
          secret:
            secretName: gcp-service-key
