apiVersion: v1
kind: Service
metadata:
  name: fake-ai-service
  namespace: tony-test
spec:
  selector:
    app: fake-ai-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      appProtocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-ai-service
  namespace: tony-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-ai-service
  template:
    metadata:
      labels:
        app: fake-ai-service
    spec:
      containers:
        - name: fake-ai-service
          image: ton731/fake-ai-service:latest
          ports:
            - containerPort: 80
