apiVersion: v1
kind: Service
metadata:
  name: fake-ai-service
  namespace: tony-test
spec:
  selector:
    app: fake-ai-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      appProtocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-ai-service
  namespace: tony-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-ai-service
  template:
    metadata:
      labels:
        app: fake-ai-service
    spec:
      containers:
        - name: fake-ai-service
          image: gcr.io/jubo-ai/ai-bedsore@sha256:c4fe7bf8f28cec6b3d5e7f1d8d48487b729fb91eb83733992c462c69253a2d5c
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: gcp-service-key
              mountPath: /app
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/gcloud-service-key.json
      volumes:
        - name: gcp-service-key
          secret:
            secretName: gcp-service-key
