apiVersion: v1
kind: Service
metadata:
  name: fake-ai-service
  namespace: stress-test
spec:
  selector:
    app: fake-ai-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      appProtocol: http
